name: highload_0224_skv_hw4_posts
services:
  spring-app:
    build: ../mainapp
    entrypoint: ["mvn", "spring-boot:run", "-Dmaven.test.skip=true"]
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5434/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.read-datasource.url=jdbc:postgresql://db:5434/postgres
      - spring.read-datasource.username=postgres
      - spring.read-datasource.password=postgres
      - app.debug.fillDbWithRandomData=true
      - app.debug.fillDbWithRandomDataThreads=200
    ports:
      - "8081:8080"
    healthcheck:
      test: "curl --fail --silent 127.0.0.1:8080/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "4.0"

  db:
    image: postgres:14-alpine
    container_name: db
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5434
    volumes:
      - ../sql/init_hw1.sql:/docker-entrypoint-initdb.d/0_init_hw1.sql
      - ../sql/index_hw2.sql:/docker-entrypoint-initdb.d/1_index_hw2.sql
      - ../sql/posts_hw4.sql:/docker-entrypoint-initdb.d/3_posts_hw4.sql
    ports:
      - "5434:5434"
    expose:
      - "5434"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3
    command: >
      postgres 
      -c ssl=off
    deploy:
      resources:
        limits:
          cpus: "4.0"