{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RPS Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_server_requests_seconds_count{error=\"none\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_server_requests_seconds_count{error!=\"none\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(method, le) (rate(http_server_requests_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}