spring:
  main:
    web-application-type: reactive
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5434/postgres'
    username: postgres
    password: postgres
  read-datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5434/postgres'
    username: postgres
    password: postgres
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 5672
server:
  port: 8081
  error:
    include-message: always
app:
  debug:
    fillDbWithRandomData: true
    fillDialogDb: true
  jwtService:
    key: "123451234512345123451234512345123451234512345123451234512345123451234512345"
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans