spring:
  cache:
    type: redis
  data:
    mongodb:
      uuid-representation: standard
server:
  port: 8083
enable-cache: true
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans