spring:
  cache:
    type: redis
  data:
    mongodb:
      uuid-representation: standard
server:
  port: 8083
enable-cache: true
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true